fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: (pre-commit|docs)/(.*)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
  - repo: https://github.com/collective/zpretty
    rev: 3.0.1
    hooks:
    -   id: zpretty
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
  - repo: local
    hooks:
      - id: code-analysis
        name: Code analysis
        entry: ${buildout:bin-directory}/code-analysis
        language: script
        files: src/ploneintranet/(.*)
        exclude: (.*).(pt|xml|zcml)
        pass_filenames: false
  - repo: https://github.com/myint/rstcheck
    rev: v6.0.0.post1
    hooks:
      - id: rstcheck
        name: rstcheck
        entry: rstcheck --ignore-messages "Duplicate explicit target name"
        language: python
        types: [rst]
